import type { EventTemplate, ServiceConfig } from "./types";

export const GAME_BALANCE = {
    saveVersion: 1,
    saveStorageKey: "rkn-clicker-save",
    maxBanCost: 100,
    eventWindowMinMs: 20_000,
    eventWindowMaxMs: 60_000,
    initialScore: 0,
    initialClickPower: 1,
    initialBasePassiveIncome: 0,
    initialBlockMultiplier: 1,
    autosaveIntervalMs: 10000,
} as const;

export const SERVICES = [
    {
        id: 'telegram',
        name: 'Telegram',
        tier: 1,
        slowCost: 10,
        slowEffect: 10,
        banCost: 20,
        banMultiplier: 2,
    },
    {
        id: 'whatsapp',
        name: 'WhatsApp',
        tier: 1,
        slowCost: 50,
        slowEffect: 50,
        banCost: 100,
        banMultiplier: 2,
    },
    {
        id: 'instagram',
        name: 'Instagram',
        tier: 1,
        slowCost: 100,
        slowEffect: 100,
        banCost: 200,
        banMultiplier: 2,
    },
    {
        id: 'youtube',
        name: 'YouTube',
        tier: 1,
        slowCost: 250,
        slowEffect: 250,
        banCost: 500,
        banMultiplier: 2,
    },
    {
        id: 'facebook',
        name: 'Facebook',
        tier: 2,
        slowCost: 500,
        slowEffect: 500,
        banCost: 1_000,
        banMultiplier: 2,
    },
    {
        id: 'x',
        name: 'X (Twitter)',
        tier: 2,
        slowCost: 1_000,
        slowEffect: 1_000,
        banCost: 2_000,
        banMultiplier: 2,
    },
    {
        id: 'discord',
        name: 'Discord',
        tier: 2,
        slowCost: 2_000,
        slowEffect: 2_000,
        banCost: 4_000,
        banMultiplier: 2,
    },
    {
        id: 'tiktok',
        name: 'TikTok',
        tier: 2,
        slowCost: 4_000,
        slowEffect: 4_000,
        banCost: 8_000,
        banMultiplier: 2,
    },
    {
        id: 'viber',
        name: 'Viber',
        tier: 3,
        slowCost: 8_000,
        slowEffect: 8_000,
        banCost: 16_000,
        banMultiplier: 3,
    },
    {
        id: 'signal',
        name: 'Signal',
        tier: 3,
        slowCost: 16_000,
        slowEffect: 16_000,
        banCost: 32_000,
        banMultiplier: 3,
    },
    {
        id: 'linkedin',
        name: 'LinkedIn',
        tier: 3,
        slowCost: 32_000,
        slowEffect: 32_000,
        banCost: 64_000,
        banMultiplier: 3,
    },
    {
        id: 'twitch',
        name: 'Twitch',
        tier: 3,
        slowCost: 64_000,
        slowEffect: 64_000,
        banCost: 128_000,
        banMultiplier: 3,
    },
    {
        id: 'steam',
        name: 'Steam',
        tier: 4,
        slowCost: 128_000,
        slowEffect: 128_000,
        banCost: 256_000,
        banMultiplier: 4,
    },
    {
        id: 'wikipedia',
        name: 'Wikipedia',
        tier: 4,
        slowCost: 256_000,
        slowEffect: 256_000,
        banCost: 512_000,
        banMultiplier: 4,
    },
    {
        id: 'reddit',
        name: 'Reddit',
        tier: 4,
        slowCost: 512_000,
        slowEffect: 512_000,
        banCost: 1_024_000,
        banMultiplier: 4,
    },
    {
        id: 'notion',
        name: 'Notion',
        tier: 4,
        slowCost: 1_024_000,
        slowEffect: 1_024_000,
        banCost: 2_048_000,
        banMultiplier: 4,
    },
    {
        id: 'github',
        name: 'GitHub',
        tier: 5,
        slowCost: 2_048_000,
        slowEffect: 2_048_000,
        banCost: 4_096_000,
        banMultiplier: 5,
    },
    {
        id: 'cloudflare',
        name: 'Cloudflare',
        tier: 5,
        slowCost: 4_096_000,
        slowEffect: 4_096_000,
        banCost: 8_192_000,
        banMultiplier: 5,
    },
    {
        id: 'google-play',
        name: 'Google Play',
        tier: 5,
        slowCost: 8_192_000,
        slowEffect: 8_192_000,
        banCost: 16_384_000,
        banMultiplier: 5,
    },
    {
        id: 'discord-cdn',
        name: 'Discord CDN',
        tier: 5,
        slowCost: 16_384_000,
        slowEffect: 16_384_000,
        banCost: 32_768_000,
        banMultiplier: 5,
    },
] as const satisfies readonly ServiceConfig[];

export const RUNTIME_LIMITS = {
    maxDeltaMs: 5000,
} as const;

export const PURCHASE_EVENTS = {
    slow: {
        id: "traffic-surge",
        name: "Паника в сети",
        multipliers: {
            clickMultiplier: 1,
            passiveMultiplier: 2,
        },
        durationMs: 20_000,
    },
    ban: {
        id: "raid-mode",
        name: "Режим ручной блокировки",
        multipliers: {
            clickMultiplier: 2,
            passiveMultiplier: 1,
        },
        durationMs: 20_000,
    },
} as const satisfies Record<"slow" | "ban", EventTemplate>;

export function getEventDelayMs(randomValue = Math.random()): number {
    const normalizedRandom = Math.min(Math.max(randomValue, 0), 1);
    const range = GAME_BALANCE.eventWindowMaxMs - GAME_BALANCE.eventWindowMinMs;

    return GAME_BALANCE.eventWindowMinMs + Math.round(range * normalizedRandom);
}

