import type { EventTemplate, ServiceConfig } from "./types";

export const GAME_BALANCE = {
    saveVersion: 1,
    saveStorageKey: "rkn-clicker-save",
    settingsStorageKey: "rkn-clicker-settings",
    maxBanCost: 100,
    eventWindowMinMs: 20_000,
    eventWindowMaxMs: 60_000,
    initialScore: 0,
    initialClickPower: 1,
    initialBasePassiveIncome: 0,
    initialBlockMultiplier: 1,
    autosaveIntervalMs: 10000,
} as const;

export const SERVICES = [
    {
        id: 'telegram',
        name: 'Telegram',
        description: 'Главный чат страны: сначала все переходят сюда, потом делают вид, что это не считается соцсетью.',
        tier: 1,
        slowCost: 10,
        slowEffect: 10,
        banCost: 20,
        banMultiplier: 2,
    },
    {
        id: 'whatsapp',
        name: 'WhatsApp',
        description: 'Семейный совет директоров интернета. Тут пересылают одно и то же сообщение с 2014 года.',
        tier: 1,
        slowCost: 50,
        slowEffect: 50,
        banCost: 100,
        banMultiplier: 2,
    },
    {
        id: 'instagram',
        name: 'Instagram',
        description: 'Святилище еды, отпусков и лиц, которые устали от собственных фильтров.',
        tier: 1,
        slowCost: 100,
        slowEffect: 100,
        banCost: 200,
        banMultiplier: 2,
    },
    {
        id: 'youtube',
        name: 'YouTube',
        description: 'Библиотека, телевидение и бездонная яма рекомендаций в одном окне.',
        tier: 1,
        slowCost: 250,
        slowEffect: 250,
        banCost: 500,
        banMultiplier: 2,
    },
    {
        id: 'facebook',
        name: 'Facebook',
        description: 'Цифровой санаторий для районных чатов, старых мемов и очень важных поздравлений с яблочным спасом.',
        tier: 2,
        slowCost: 500,
        slowEffect: 500,
        banCost: 1_000,
        banMultiplier: 2,
    },
    {
        id: 'x',
        name: 'X (Twitter)',
        description: 'Место, где каждый срочно эксперт, а кнопка переименования всё ещё переживается тяжелее реформ.',
        tier: 2,
        slowCost: 1_000,
        slowEffect: 1_000,
        banCost: 2_000,
        banMultiplier: 2,
    },
    {
        id: 'discord',
        name: 'Discord',
        description: 'Голосовой подъезд интернета: шумно, многолюдно и у каждого свой очень срочный сервер.',
        tier: 2,
        slowCost: 2_000,
        slowEffect: 2_000,
        banCost: 4_000,
        banMultiplier: 2,
    },
    {
        id: 'tiktok',
        name: 'TikTok',
        description: 'Вертикальная бездна, где план на пять минут стабильно превращается в потерянный вечер.',
        tier: 2,
        slowCost: 4_000,
        slowEffect: 4_000,
        banCost: 8_000,
        banMultiplier: 2,
    },
    {
        id: 'viber',
        name: 'Viber',
        description: 'Уютный архив эпохи, когда каждый мессенджер обещал быть главным и даже в это верил.',
        tier: 3,
        slowCost: 8_000,
        slowEffect: 8_000,
        banCost: 16_000,
        banMultiplier: 3,
    },
    {
        id: 'signal',
        name: 'Signal',
        description: 'Приложение, которое звучит как шпионский роман и поэтому всем кажется особенно серьёзным.',
        tier: 3,
        slowCost: 16_000,
        slowEffect: 16_000,
        banCost: 32_000,
        banMultiplier: 3,
    },
    {
        id: 'linkedin',
        name: 'LinkedIn',
        description: 'Торжественная ярмарка делового оптимизма, где все одновременно вдохновлены и открыты к новым вызовам.',
        tier: 3,
        slowCost: 32_000,
        slowEffect: 32_000,
        banCost: 64_000,
        banMultiplier: 3,
    },
    {
        id: 'twitch',
        name: 'Twitch',
        description: 'Круглосуточный фестиваль реакций, донатов и обещаний уйти спать сразу после ещё одного стрима.',
        tier: 3,
        slowCost: 64_000,
        slowEffect: 64_000,
        banCost: 128_000,
        banMultiplier: 3,
    },
    {
        id: 'steam',
        name: 'Steam',
        description: 'Магазин скидок, замаскированный под игровую платформу. Бэклог там растёт быстрее экономики.',
        tier: 4,
        slowCost: 128_000,
        slowEffect: 128_000,
        banCost: 256_000,
        banMultiplier: 4,
    },
    {
        id: 'wikipedia',
        name: 'Wikipedia',
        description: 'Коллективная память человечества, которую все цитируют и одновременно учат не цитировать.',
        tier: 4,
        slowCost: 256_000,
        slowEffect: 256_000,
        banCost: 512_000,
        banMultiplier: 4,
    },
    {
        id: 'reddit',
        name: 'Reddit',
        description: 'Город форумов, где можно найти ответ на любой вопрос и сразу же три повода пожалеть, что спросил.',
        tier: 4,
        slowCost: 512_000,
        slowEffect: 512_000,
        banCost: 1_024_000,
        banMultiplier: 4,
    },
    {
        id: 'notion',
        name: 'Notion',
        description: 'Место, где люди строят идеальную систему продуктивности вместо того, чтобы просто сделать задачу.',
        tier: 4,
        slowCost: 1_024_000,
        slowEffect: 1_024_000,
        banCost: 2_048_000,
        banMultiplier: 4,
    },
    {
        id: 'github',
        name: 'GitHub',
        description: 'Священное хранилище коммитов, где баги получают историю изменений и публичную биографию.',
        tier: 5,
        slowCost: 2_048_000,
        slowEffect: 2_048_000,
        banCost: 4_096_000,
        banMultiplier: 5,
    },
    {
        id: 'cloudflare',
        name: 'Cloudflare',
        description: 'Интернетовский турникет: сначала докажи, что ты не робот, потом уже страдай дальше.',
        tier: 5,
        slowCost: 4_096_000,
        slowEffect: 4_096_000,
        banCost: 8_192_000,
        banMultiplier: 5,
    },
    {
        id: 'google-play',
        name: 'Google Play',
        description: 'Витрина, где полезные приложения соседствуют с фонариками, которые требуют доступ ко всей жизни.',
        tier: 5,
        slowCost: 8_192_000,
        slowEffect: 8_192_000,
        banCost: 16_384_000,
        banMultiplier: 5,
    },
    {
        id: 'discord-cdn',
        name: 'Discord CDN',
        description: 'Склад картинок, мемов и вложений, без которого половина интернета внезапно начинает выглядеть пустой.',
        tier: 5,
        slowCost: 16_384_000,
        slowEffect: 16_384_000,
        banCost: 32_768_000,
        banMultiplier: 5,
    },
] as const satisfies readonly ServiceConfig[];

export const RUNTIME_LIMITS = {
    maxDeltaMs: 5000,
} as const;

export const PURCHASE_EVENTS = {
    slow: {
        id: "traffic-surge",
        name: "Паника в сети",
        multipliers: {
            clickMultiplier: 1,
            passiveMultiplier: 2,
        },
        durationMs: 20_000,
    },
    ban: {
        id: "raid-mode",
        name: "Режим ручной блокировки",
        multipliers: {
            clickMultiplier: 2,
            passiveMultiplier: 1,
        },
        durationMs: 20_000,
    },
} as const satisfies Record<"slow" | "ban", EventTemplate>;

export function getEventDelayMs(randomValue = Math.random()): number {
    const normalizedRandom = Math.min(Math.max(randomValue, 0), 1);
    const range = GAME_BALANCE.eventWindowMaxMs - GAME_BALANCE.eventWindowMinMs;

    return GAME_BALANCE.eventWindowMinMs + Math.round(range * normalizedRandom);
}
